AddPopupMaxProtonNeutron
AliMatias/SIAMM pull request #50
Opened 2019-08-22 04:49 UTC by mgallo2019

Se agregan popup de limites MAXIMOS para neutrones y protones. NO DEJANDO agregar mas una vez llegado a ese limite. segun se hablo con el grupo.

2019-08-22 05:06 UTC, mgallo2019 commented
#35 referencia a este issue

2019-08-22 14:44 UTC, mgallo2019 commented
En la escena en el panel moleculas se habilita el rich text en la lista despl. y en el boton agregar habia un return que hacia que el texto este desalineado

2019-08-22 23:34 UTC, ldgobbi requested changes

2019-08-22 23:34 UTC, ldgobbi commented on New Unity Project/Assets/Scripts/Elements/Atom.cs
> +            if (allowProtonSpawn)
No esta funcionando. Si bien aparece el mensaje, me deja seguir agregando protones y neutrones.

Esto pasa porque el **GameObject de la partícula se instancia y posiciona antes** del `if (proton)` (líneas 81 a 87 no deberían ocurrir si el allow esta en false), lo unico que me bloquea esta línea es que no se agrega a la cola de protonos o neutrones, lo que resulta en que si agregué mas partículas de las permitidas tampoco se van a eliminar cuando las quite.

2019-08-23 00:20 UTC, ldgobbi approved these changes

2019-08-23 00:20 UTC, merged